services:
  postgres:
    image: postgres:16-alpine
    container_name: insight-db
    restart: always
    environment:
      POSTGRES_USER: insight_admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /opt/insight/data/03-databases/postgres:/var/lib/postgresql/data
    networks:
      - ${DOCKER_NETWORK_NAME:-insight-net}
    deploy:
      resources:
        limits:
          memory: 2G  # 给数据库预留最高 2G 内存

networks:
  insight-net:
    external: true
