services:
  nocodb:
    image: nocodb/nocodb:latest
    container_name: insight-nocodb
    restart: always
    environment:
      NC_DB: "pg://${DB_HOST:-insight-db}:${DB_PORT:-5432}?u=${DB_USER:-insight_admin}&p=${DB_PASSWORD}&d=nocodb_db"
    volumes:
      - /opt/insight/data/05-data-viz:/usr/app/data
    networks:
      - ${DOCKER_NETWORK_NAME:-insight-net}

networks:
  insight-net:
    external: true
