services:
  wiki:
    image: requarks/wiki:2
    container_name: insight-wiki
    restart: always
    # 必须添加下面这两行，否则外部（包括浏览器和宿主机防火墙）看不到 3000 端口
    ports:
      - "${WIKIJS_PORT:-3000}:3000"
    environment:
      DB_TYPE: postgres
      DB_HOST: ${DB_HOST:-insight-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-insight_admin}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: wikijs_db
    volumes:
      - /opt/insight/data/06-knowledge:/wiki/storage
    networks:
      - ${DOCKER_NETWORK_NAME:-insight-net}

networks:
  insight-net:
    external: true
